[package]
name = "torchsnap"
version = "0.1.0"
description = "torchsnap"
authors = ["Jakob Westhoff <jakob@westhoffswelt.de> (https://westhoffswelt.de)"]
edition = "2024"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "torchsnap_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-process = "2"
anyhow = "1"
serde = { version = "1.0.228", features = ["derive"] }
nucleo-matcher = "0.3.1"
plist = "1.8.0"
rayon = "1.11.0"

[target.'cfg(target_os = "macos")'.dependencies]
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", branch = "v2.1" }
objc2-app-kit = { version = "0.3.2", features = ["NSWindow"] }
