// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// =========================================================
// Capability Types
//
// Each capability is a self-contained type that holds both
// the underlying implementation and any permission
// configuration. Permission checking happens inside the
// capability — callers never need to pre-check.
//
// The `ProvisionedCaps` struct bundles all capabilities for
// a single gadget instance. Each field is `Option<Arc<...>>`
// — present if the gadget requested the capability, absent
// if it didn't. The `cap_accessor!` macro generates typed
// accessor methods that panic with a clear message if the
// capability wasn't provisioned.
// =========================================================

use std::sync::Arc;

mod clipboard;
mod command;
mod filesystem;
mod frecency;
mod http;
mod icon_cache;
mod opener;
mod path_resolver;
mod settings;
mod sql_storage;
mod website_metadata;

pub use clipboard::*;
pub use command::*;
pub use filesystem::*;
pub use frecency::*;
pub use http::*;
pub use icon_cache::*;
pub use opener::*;
pub use path_resolver::*;
pub use settings::*;
pub use sql_storage::*;
pub use website_metadata::*;

// =========================================================
// cap_accessor! macro
// =========================================================

macro_rules! cap_accessor {
    ($name:ident -> $ty:ty) => {
        pub fn $name(&self) -> &Arc<$ty> {
            self.$name.as_ref().expect(concat!(
                stringify!($ty),
                " not provisioned — did you declare it in requested_caps()?"
            ))
        }
    };
}

// =========================================================
// ProvisionedCaps
// =========================================================

/// Bundle of capabilities for a single gadget instance.
///
/// Each field is `None` if the gadget did not request the
/// capability. Accessor methods generated by `cap_accessor!`
/// panic with a clear message if the capability is absent.
pub struct ProvisionedCaps {
    pub opener: Option<Arc<OpenerCap>>,
    pub http: Option<Arc<HttpCap>>,
    pub filesystem: Option<Arc<FilesystemCap>>,
    pub command: Option<Arc<CommandCap>>,
    pub clipboard: Option<Arc<ClipboardCap>>,
    pub sql_storage: Option<Arc<SqlStorageCap>>,
    pub website_metadata: Option<Arc<WebsiteMetadataCap>>,
    pub icon_cache: Option<Arc<IconCacheCap>>,
    pub settings: Option<Arc<SettingsCap>>,
    pub frecency: Option<Arc<FrecencyCap>>,
    pub path_resolver: Option<Arc<PathResolverCap>>,
}

impl ProvisionedCaps {
    cap_accessor!(opener -> OpenerCap);
    cap_accessor!(http -> HttpCap);
    cap_accessor!(filesystem -> FilesystemCap);
    cap_accessor!(command -> CommandCap);
    cap_accessor!(clipboard -> ClipboardCap);
    cap_accessor!(sql_storage -> SqlStorageCap);
    cap_accessor!(website_metadata -> WebsiteMetadataCap);
    cap_accessor!(icon_cache -> IconCacheCap);
    cap_accessor!(settings -> SettingsCap);
    cap_accessor!(frecency -> FrecencyCap);
    cap_accessor!(path_resolver -> PathResolverCap);
}

// =========================================================
// CapRequest
// =========================================================

/// Declares a single capability a gadget needs. Provided at
/// registration time — the host builds `ProvisionedCaps` from
/// a `Vec<CapRequest>`.
///
/// Struct variants use named `permissions` / `config` fields
/// to maintain an explicit structural division between
/// security-relevant permission data and non-security
/// construction data. Unit variants are for caps that need
/// neither.
pub enum CapRequest {
    Opener {
        permissions: OpenerPermissions,
    },
    Http {
        permissions: HttpPermissions,
    },
    Filesystem {
        permissions: FilesystemPermissions,
    },
    Command {
        permissions: CommandPermissions,
    },
    SqlStorage {
        config: SqlStorageConfig,
    },
    Clipboard,
    WebsiteMetadata,
    IconCache,
    Settings,
    Frecency,
    PathResolver,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cap_request_opener_variant() {
        let req = CapRequest::Opener {
            permissions: OpenerPermissions {
                schemes: vec!["https".into()],
                open_path: false,
                reveal_path: true,
            },
        };
        match req {
            CapRequest::Opener { permissions } => {
                assert_eq!(permissions.schemes, vec!["https"]);
                assert!(!permissions.open_path);
                assert!(permissions.reveal_path);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn cap_request_http_variant() {
        let req = CapRequest::Http {
            permissions: HttpPermissions {
                origins: vec!["https://example.com".into()],
            },
        };
        match req {
            CapRequest::Http { permissions } => {
                assert_eq!(permissions.origins, vec!["https://example.com"]);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn cap_request_filesystem_variant() {
        let req = CapRequest::Filesystem {
            permissions: FilesystemPermissions {
                read_patterns: vec!["${home}/*.txt".into()],
            },
        };
        match req {
            CapRequest::Filesystem { permissions } => {
                assert_eq!(permissions.read_patterns.len(), 1);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn cap_request_command_variant() {
        let req = CapRequest::Command {
            permissions: CommandPermissions {
                rules: vec![],
            },
        };
        match req {
            CapRequest::Command { permissions } => {
                assert!(permissions.rules.is_empty());
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn cap_request_sql_storage_variant() {
        let req = CapRequest::SqlStorage {
            config: SqlStorageConfig {
                migrations: vec!["CREATE TABLE t (id INT);".into()],
            },
        };
        match req {
            CapRequest::SqlStorage { config } => {
                assert_eq!(config.migrations.len(), 1);
                assert_eq!(config.migrations[0], "CREATE TABLE t (id INT);");
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn cap_request_unit_variants() {
        let variants: Vec<CapRequest> = vec![
            CapRequest::Clipboard,
            CapRequest::WebsiteMetadata,
            CapRequest::IconCache,
            CapRequest::Settings,
            CapRequest::Frecency,
            CapRequest::PathResolver,
        ];
        assert_eq!(variants.len(), 6);
    }

    #[test]
    fn cap_request_is_send_and_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<CapRequest>();
    }
}
