// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// =========================================================
// Capability Types
//
// Each capability is a self-contained type that holds both
// the underlying implementation and any permission
// configuration. Permission checking happens inside the
// capability — callers never need to pre-check.
//
// The `ProvisionedCaps` struct bundles all capabilities for
// a single gadget instance. Each field is `Option<Arc<...>>`
// — present if the gadget requested the capability, absent
// if it didn't. The `cap_accessor!` macro generates typed
// accessor methods that panic with a clear message if the
// capability wasn't provisioned.
// =========================================================

use std::sync::Arc;

mod clipboard;
mod command;
mod filesystem;
mod frecency;
mod http;
mod icon_cache;
mod opener;
mod path_resolver;
mod settings;
mod sql_storage;
mod website_metadata;

pub use clipboard::*;
pub use command::*;
pub use filesystem::*;
pub use frecency::*;
pub use http::*;
pub use icon_cache::*;
pub use opener::*;
pub use path_resolver::*;
pub use settings::*;
pub use sql_storage::*;
pub use website_metadata::*;

// =========================================================
// cap_accessor! macro
// =========================================================

macro_rules! cap_accessor {
    ($name:ident -> $ty:ty) => {
        pub fn $name(&self) -> &Arc<$ty> {
            self.$name.as_ref().expect(concat!(
                stringify!($ty),
                " not provisioned — did you declare it in requested_caps()?"
            ))
        }
    };
}

// =========================================================
// ProvisionedCaps
// =========================================================

/// Bundle of capabilities for a single gadget instance.
///
/// Each field is `None` if the gadget did not request the
/// capability. Accessor methods generated by `cap_accessor!`
/// panic with a clear message if the capability is absent.
pub struct ProvisionedCaps {
    pub opener: Option<Arc<OpenerCap>>,
    pub http: Option<Arc<HttpCap>>,
    pub filesystem: Option<Arc<FilesystemCap>>,
    pub command: Option<Arc<CommandCap>>,
    pub clipboard: Option<Arc<ClipboardCap>>,
    pub sql_storage: Option<Arc<SqlStorageCap>>,
    pub website_metadata: Option<Arc<WebsiteMetadataCap>>,
    pub icon_cache: Option<Arc<IconCacheCap>>,
    pub settings: Option<Arc<SettingsCap>>,
    pub frecency: Option<Arc<FrecencyCap>>,
    pub path_resolver: Option<Arc<PathResolverCap>>,
}

impl ProvisionedCaps {
    cap_accessor!(opener -> OpenerCap);
    cap_accessor!(http -> HttpCap);
    cap_accessor!(filesystem -> FilesystemCap);
    cap_accessor!(command -> CommandCap);
    cap_accessor!(clipboard -> ClipboardCap);
    cap_accessor!(sql_storage -> SqlStorageCap);
    cap_accessor!(website_metadata -> WebsiteMetadataCap);
    cap_accessor!(icon_cache -> IconCacheCap);
    cap_accessor!(settings -> SettingsCap);
    cap_accessor!(frecency -> FrecencyCap);
    cap_accessor!(path_resolver -> PathResolverCap);
}
